### ISSUE TITLE
Error reading in TTS file

### ISSUE THREAD

**Issue by bryce-sharman** [sap-toronto/gtam-tools#3]
I had an error reading in the following file produced by iDRS

[persons_all.txt](https://github.com/sap-toronto/gtam-tools/files/11848576/persons_all.txt)

The issue is in the helper function, shown below. The ```pd.read_csv()``` returns a ```KeyError```, and not a ```ValueError``` in this case.  The code seems to work in this case when I replace the exception with a more general test, such as ```except Exception:```, but I admit that's not a good coding practice so I'll leave it up to you all as to how you want to fix this.

```
def _read_csv_tts_ct_data(fp: Path, row_att: str, col_att: str, skip_rows: int, **kwargs) -> pd.DataFrame:
    try:  # First try column format
        df = pd.read_csv(fp, index_col=[row_att, col_att], skiprows=skip_rows, delim_whitespace=True, **kwargs)
    except ValueError:  # Else try table format
        df = pd.read_csv(fp, index_col=0, skiprows=skip_rows, **kwargs)
        df.index.name = row_att
        df.columns.name = col_att
        df = df.stack().to_frame(name='total')
    df.reset_index(inplace=True)

    return df
```

**Comment by bccheung** [comment]
Can you please provide the pandas version you are using? They probably changed the exception type in newer versions.

**Comment by bryce-sharman** [comment]
'1.5.3'
